# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [2]:
s = "Hi there Sam!"
word = s.split() 
print(word)

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [5]:
text = "the diameter of {planet} is {diameter} kilometers".format(planet = "Earth",diameter = 12742)
print(text)

the diameter of Earth is 12742 kilometers

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [1]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [2]:
import numpy as np
array=np.zeros(10)
print(array)

ModuleNotFoundError: No module named 'numpy'

In [ ]:
import numpy as np
array=np.zeros(10)*5
print(array)

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arange(20,35,2)
print(array)

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
array=np.arange(0,9).reshape(3,3)
print(array)

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [3]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
arr = np.concatenate((a,b))
print(arr)

ModuleNotFoundError: No module named 'numpy'

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd 
data = [[1,2],[3,4],[5,6]]
df = pd.DataFrame(data)
print(df)

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as pd 
per1 = pd.date_range(start='1-1-2023',end='2-10-2023')
for val in per1:
    print(val)

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists,columns=['Fname','Lname','Age'])
print(df)